GaloyMoney/lana-bank

- lana/app/src/credit_facility/entity.rs
- lana/app/src/terms/value.rs
This makes it so that the check falls back to the `total` cvl in `FacilityCVL` since that value will always be lower than the `disbursed` cvl.
The issue here was that with a structuring fee of `0` the projected cvl had a `disbursed` value of 0 which caused the activation job to error [here](https://github.com/GaloyMoney/lana-bank/blob/5d4e539fc0b5c19db893e0558657a08733b34ed2/lana/app/src/credit_facility/processes/activate_credit_facility/mod.rs#L90).
> fix: handle zero disbursed amount for check_disbursal function

- apps/admin-panel/app/command-menu.tsx
- apps/admin-panel/app/create.tsx
- apps/admin-panel/app/credit-facilities/[credit-facility-id]/layout.tsx
- apps/admin-panel/app/credit-facilities/create.tsx
- apps/admin-panel/app/customers/[customer-id]/details.tsx
- apps/admin-panel/app/customers/[customer-id]/layout.tsx
- apps/admin-panel/app/customers/create.tsx
- apps/admin-panel/app/layout.tsx
- apps/admin-panel/components/app-sidebar/index.tsx
- apps/admin-panel/components/app-sidebar/nav-section.tsx
- apps/admin-panel/components/app-sidebar/user-block.tsx
- apps/admin-panel/components/breadcrumb-wrapper.tsx
- apps/admin-panel/components/data-table/index.tsx
- apps/admin-panel/components/paginated-table/index.tsx
- apps/admin-panel/hooks/use-tab-navigation.tsx
- apps/admin-panel/package.json
- apps/admin-panel/pnpm-lock.yaml
- apps/admin-panel/ui/command.tsx
+ Open the command window with actions: `cmd + k`
+ Open the command window with navigation options only: `Shift + n`
+ Use the up and down arrows to navigate in the table component.
+ Use the right and left arrow buttons to navigate between tabs on the Customer and Credit Facility pages.
TODO 
> + Open the command window with actions: `cmd + k` 
> + Open the command window with navigation options only: `Shift + n`
add these instructions in app
> feat: implement command menu for keyboard navigation

- core/chart-of-accounts/src/chart_of_accounts/entity.rs
- core/chart-of-accounts/src/lib.rs
- core/chart-of-accounts/src/path/error.rs
- core/chart-of-accounts/src/path/mod.rs
- core/chart-of-accounts/src/primitives.rs
- core/chart-of-accounts/src/transaction_account_factory.rs
- core/chart-of-accounts/tests/chart_of_accounts.rs
- core/deposit/src/ledger/mod.rs
- core/deposit/tests/deposit.rs
- core/deposit/tests/withdraw.rs
- lana/app/src/accounting_init/mod.rs
- lana/app/src/accounting_init/primitives.rs
- lana/app/src/accounting_init/seed.rs
- lana/app/src/credit_facility/ledger/mod.rs
This PR is to:
- rename 'code' concept to 'path'
- remove 'decoding' of stringified path and instead store as value in `Path` type
- separate `Category` from `Path` type (and refactor `index` on category)
- break up `ChartPath` enum into separate structs
> refactor: change chart 'code' abstraction to 'path'

- core/chart-of-accounts/src/chart_of_accounts/entity.rs
- core/chart-of-accounts/src/error.rs
- core/chart-of-accounts/src/lib.rs
- core/chart-of-accounts/src/path/error.rs
- core/chart-of-accounts/src/path/mod.rs
- core/chart-of-accounts/src/primitives.rs
- core/chart-of-accounts/src/transaction_account_factory.rs
- core/chart-of-accounts/tests/chart_of_accounts.rs
- core/deposit/src/primitives.rs
- core/deposit/tests/deposit.rs
- core/deposit/tests/withdraw.rs
- lana/app/src/accounting_init/mod.rs
- lana/app/src/accounting_init/primitives.rs
- lana/app/src/accounting_init/seed.rs
- lana/app/src/app/mod.rs
~**_DO NOT MERGE_ before #1248**~
Transaction accounts aren't tracked in the chart. They don't get a GL code, and are simply detail accounts for the control sub-account they fall under.
The `add_transaction_account` is a no-op after this PR with a note to tie it back to the chart by using some sort of a `ControlSubAccount` entity representation to track member accounts added to it
> chore: remove chart transaction account

- flake.nix
This change ensures that any additional arguments passed to the `meltano` alias command are correctly forwarded.
* [`flake.nix`](diffhunk://#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0L37-R37): Modified the `meltano` alias to include `"$@"` to forward additional arguments.
> fix: meltano alias in flake

- meltano/transform/models/staging/stg_credit_facility_events.sql
This is necessary for holistics since otherwise we would have to grant the service account permission to query even our raw data.
> chore(reporting): materialize raw credit facility events

- bats/z-report.bats
- lana/app/src/report/config.rs
- lana/app/src/report/upload.rs
The code that compiles and executes the dataform workflow still needs to be removed.
> chore: query dbt reports instead of dataform reports

- lana/app/src/balance_sheet/ledger/mod.rs
- lana/app/src/profit_and_loss/ledger/mod.rs
- lana/app/src/trial_balance/ledger/mod.rs
This is to allow the read-only transaction to rollback (via Drop) instead of explicitly committing and possible having an error thrown if there was another update elsewhere. Read needs to be internally consistent, but not necessarily at the latest state of the db.
> chore: remove statements db-op commits

- meltano/transform/models/staging/stg_account_balances.sql
- meltano/transform/models/staging/stg_account_set_member_account_sets.sql
- meltano/transform/models/staging/stg_account_set_member_accounts.sql
- meltano/transform/models/staging/stg_account_sets.sql
- meltano/transform/models/staging/stg_accounts.sql
- meltano/transform/models/staging/stg_credit_facility_events.sql
- meltano/transform/models/staging/stg_customer_events.sql
Even without real production data, many of the source tables created by `tap-postgres` are already hundreds of thousands of rows long. This might not be an issue once incremental loading is configured, but in the meantime this is a simple fix that will prevent running dbt from taking too long in the future.
> chore(reporting): configure incremental updates for staging models

- lana/app/src/credit_facility/entity.rs
- lana/app/src/credit_facility/repayment_plan.rs
This is not equivilent to the Disbursal and Withdrawal entities where the approval_process_id is recorded in the Initialized event.
> chore: remove ApprovalProcessStarted event from credit facility

- meltano/transform/models/sources.yml
- meltano/transform/models/staging/stg_account_balances.sql
- meltano/transform/models/staging/stg_account_set_member_account_sets.sql
- meltano/transform/models/staging/stg_account_set_member_accounts.sql
- meltano/transform/models/staging/stg_account_sets.sql
- meltano/transform/models/staging/stg_accounts.sql
- meltano/transform/models/staging/stg_bitfinex_order_book.sql
- meltano/transform/models/staging/stg_bitfinex_trades.sql
- meltano/transform/models/staging/stg_credit_facility_events.sql
- meltano/transform/models/staging/stg_customer_events.sql
A merged PR will reset the data warehouse so its state is synced with the application: https://github.com/GaloyMoney/galoy-deployments/pull/148
This PR caches the price as well as trades and order book data so that we can keep historical values through the reset.
> chore(reporting): cache market data from bitfinex

- tf/bq-setup/bq.tf
This PR configures the dbt dataset as an authorized dataset to our raw dataset.  This means that, though the holistics service account can't query the raw dataset, any views we create in the dbt dataset which point to the raw dataset can be queried by holistics.  This means we can get live prices and other nice things.
> feat(reporting): enable live views for holistics

- apps/admin-panel/lib/graphql/generated/index.ts
- apps/admin-panel/lib/graphql/generated/mocks.ts
- core/chart-of-accounts/src/chart_of_accounts/entity.rs
- core/chart-of-accounts/src/chart_of_accounts/mod.rs
- core/chart-of-accounts/src/lib.rs
- lana/admin-server/src/graphql/chart_of_accounts.rs
- lana/admin-server/src/graphql/loader.rs
- lana/admin-server/src/graphql/schema.graphql
- lana/admin-server/src/graphql/schema.rs
- lana/admin-server/src/primitives.rs
- lana/app/src/lib.rs
- lana/app/src/primitives.rs
This is to add the missing elements to the `ChartOfAccounts` gql type in prep for using it with the `exec_mutation!` macro
> refactor: make charts gql type into an entity

- meltano/meltano.yml
- meltano/transform/dbt_project.yml
We could configure test results to go to their own dataset but I don't think there is any benefits from the additional complexity in the terraform configuration.
> chore(reporting): configure dbt data tests to run daily and store results

- meltano/transform/models/intermediate/credit_facilities_alt/int_credit_facilities_alt.yml
- meltano/transform/models/outputs/credit_facilities_alt/credit_facilities.sql
- meltano/transform/models/outputs/credit_facilities_alt/credit_facilities_alt.yml
- meltano/transform/models/staging/stg_accounts.yml
- meltano/transform/tests/credit_facilities_alt/assert_disbursals_less_than_facility.sql
- meltano/transform/tests/credit_facilities_alt/assert_liquidation_cvl.sql
Since the schema for events is still evolving, assumptions used in the data warehouse can break down.  Adding data tests is a good way to make sure that the assumptions our data models depend on hold or (once https://github.com/GaloyMoney/lana-bank/pull/1449 is merged) know when they don't.
> feat(reporting): data tests for alternative credit facility tables

- tf/bq-setup/service-account.tf
This is necessary to see how our dbt queries perform and identify any problematic queries.  Recently started seeing some concerning performance with some of the queries used in the models and I want to get more information.
See: https://cloud.google.com/bigquery/docs/information-schema-jobs
> chore(reporting): enable INFORMATION_SCHEMA.JOBS view

- meltano/transform/models/outputs/credit_facilities_alt/daily_credit_facility_states.sql
When the collateral change is 0 the average open price UDF returns 0 this caused the alt collateral dashboard to show a price below the lowest price seen for the average open price when taking the average over credit facilities (since some were set to 0 instead of NULL)
> fix(reporting): average open price should not be zero

- core/chart-of-accounts/src/new/csv.rs
- core/chart-of-accounts/src/new/entity.rs
- core/chart-of-accounts/src/new/mod.rs
- core/chart-of-accounts/src/new/primitives.rs
- core/chart-of-accounts/src/new/tree.rs
This PR is to remove the opinionated `Category`/`ControlAccount`/`ControlSubAccount` hierarchy and to instead use a more generic `Node` element to represent nodes and levels in the chart
> refactor: genericize new charts structure

- meltano/meltano.yml
Since we're using incremental loading for sumsub (only make an api call when there are new rows in the sumsub_callbacks table) this should not cause issues with the API limits.
> chore(reporting): sync sumsub data every two minutes

- lana/app/src/report/error.rs
- lana/app/src/report/upload.rs
- lana/app/src/service_account/error.rs
- lana/app/src/service_account/mod.rs
- lana/app/tests/gcs.rs
- lana/cli/src/config.rs
- lana/cli/src/lib.rs
will looks like this
for reports:
for documents:
> chore: make it running without GCP env

- apps/admin-panel/app/modules/credit-config-update.tsx
- apps/admin-panel/app/modules/page.tsx
- apps/admin-panel/i18n.lock
- apps/admin-panel/lib/graphql/generated/index.ts
- apps/admin-panel/lib/graphql/generated/mocks.ts
- apps/admin-panel/messages/en.json
- apps/admin-panel/messages/es.json
- core/credit/src/chart_of_accounts_integration.rs
- core/credit/src/ledger/constants.rs
- core/credit/src/ledger/mod.rs
- core/credit/src/lib.rs
- core/credit/src/primitives.rs
- core/credit/tests/chart_of_accounts_integration.rs
- lana/admin-server/src/graphql/credit_config.rs
- lana/admin-server/src/graphql/schema.graphql
- lana/admin-server/src/graphql/schema.rs
This is to expand the number of internal credit module account sets to accommodate different kinds of loan receivable chart accounts
> feat: expand credit internal account sets

- dev/Tiltfile
I don't think we need to wait for `core` to be up to start compile apps. it's not like compiling apps would fail is core is not up, and doing both in parrallel would accelerate the overall compile time
> chore: not waiting for core to compile pnpm apps

- bats/z-report.bats
- lana/app/src/report/upload.rs
Report generation was failing because find_report_outputs was not finding the report tables.  The problem was that the list tables call needs paging to go through all the tables.
> fix: add paging for find_report_outputs

- meltano/extract/tap-sumsubapi/tap_sumsubapi/postgres_client.py
Used double quotes `"` as in bigquery sql instead of single quotes `'` for strings.
> fix(reporting): sql mistake causing tap-sumsubapi to fail

- core/accounting/src/primitives.rs
- lana/app/src/authorization/seed.rs
After renaming General Ledger into Journal, including relevant permissions, permissions for reading journal were not added to the seed. This patch adds them.
Before:
After:
> chore: Add journal-related permissions to authorization seed

- core/accounting/src/journal/error.rs
During renaming of General Ledger into Journal, this was omitted.
> chore: Fix textual representation of JournalError

- core/credit/src/credit_facility/entity.rs
- core/credit/src/credit_facility/interest_outstanding.rs
- core/credit/src/credit_facility/repayment_plan.rs
- core/credit/src/jobs/interest_accrual_cycles.rs
- core/credit/src/jobs/mod.rs
- core/credit/src/jobs/obligation_due.rs
- core/credit/src/jobs/obligation_overdue.rs
- core/credit/src/jobs/overdue.rs
- core/credit/src/lib.rs
- core/credit/src/obligation/entity.rs
- core/credit/src/obligation/error.rs
- core/credit/src/obligation/repo.rs
- core/credit/src/primitives.rs
- core/credit/src/processes/activate_credit_facility/mod.rs
- core/credit/src/processes/approve_disbursal/mod.rs
Note: after #1726 is merged, can rebase with `git rebase --onto main obligations` locally after pulling the updated `main` branch
This PR introduces `MarkedDue` and `MarkedOverdue` events and updates them in the respective use-cases/jobs
> feat: add Obligation due events

- meltano/meltano.yml
There are errors on staging due to a scheduled job failing because the last instance has not finished.
> fix(reporting): reduce the frequency for some meltano jobs

- apps/admin-panel/lib/graphql/generated/index.ts
- apps/admin-panel/lib/graphql/generated/mocks.ts
- bats/accounting.bats
- core/accounting/src/lib.rs
- core/accounting/src/manual_transaction/ledger/template.rs
- core/accounting/src/manual_transaction/mod.rs
- core/accounting/tests/manual_transaction.rs
- lana/admin-server/src/graphql/accounting/manual_transaction.rs
- lana/admin-server/src/graphql/schema.graphql
- lana/admin-server/src/graphql/schema.rs
- lana/admin-server/src/primitives.rs
The effective date is optional on GraphQL level, so users are not required to provide it. If they don't provide it, current date is used.
This only allows to pass effective date from user and store it in the transaction's parameters. The effective date has no effect (😛) on calculations yet.
> chore: Allow to set effective date when creating manual transaction

- apps/admin-panel/app/credit-facilities/[credit-facility-id]/disbursals/list.tsx
- apps/admin-panel/app/credit-facilities/[credit-facility-id]/repayment-plan/list.tsx
- apps/admin-panel/app/credit-facilities/[credit-facility-id]/transaction.tsx
- apps/admin-panel/app/journal/execute-manual-transaction.tsx
- apps/admin-panel/app/ledger-account/[ledger-account-ref]/page.tsx
- apps/admin-panel/app/ledger-transaction/[ledger-transaction-id]/page.tsx
- apps/admin-panel/components/data-table/index.tsx
- apps/admin-panel/components/paginated-table/index.tsx
Removing this as it’s causing scrolling issues similar to this: https://github.com/GaloyMoney/galoy-wip/issues/216. 
Also, it’s already disabled in most places, so I believe we don’t need it for now.
> chore: remove auto-focus from tables

- core/credit/src/interest_accrual_cycle/entity.rs
- core/credit/src/jobs/obligation_due.rs
- core/credit/src/obligation/entity.rs
Interest is only ever due and there are no obvious actions/requirements for an overdue state so this is removed here.
In future we may want to re-introduce an overdue state for things like sending late payment notifications, or to warn of upcoming default etc.
> chore: remove interest overdue state

- AUTH.md
- Dockerfile.release
- Makefile
- ci/pipeline.yml
- ci/tasks/check-code-apps.sh
- ci/tasks/github-release.sh
- ci/values.yml
- ci/vendor/pipeline-fragments.lib.yml
- pnpm-workspace.yaml
local cargo is cargo 1.86.0
runtime is based on 1.78.0
what is the right strategy here to keep in sync? 
I think it's better to target stable as opposed to a defined version? on flake update we algo __generally__ stays on stable
some items done here:
- doing check code for apps (we were not doing it)
- not using nix anymore for building rust (save about ~12 min to fetch/build nix deps)
- pre-emptively compiling release build
- removing debug build: not used/not tagged
> ci: discrepency between local cargo and deployed cargo

- Makefile
Broke due to this : https://github.com/GaloyMoney/lana-bank/commit/0ac58afeea5ceacbd86e6de133eb1bb522265358 
We need to use `full-sdl` so that we trigger codegen, which will fail the check-code if we use incorrect GraphQL in the front end.
> fix: check-code sdl

- meltano/meltano.yml
- meltano/transform/macros/util/drop_old_relations.sql
There's a bug in the regulatory reports screen where the old versions of reports we've renamed are still showing up because dbt doesn't automatically delete the old tables for renamed queries.
This PR adds a macro to do this automatically on a weekly basis.
> feat(reporting): dbt macro to drop stale tables

- apps/admin-panel/app/balance-sheet/page.tsx
- apps/admin-panel/app/ledger-account/[ledger-account-ref]/page.tsx
- apps/admin-panel/app/profit-and-loss/page.tsx
- apps/admin-panel/app/trial-balance/page.tsx
- apps/admin-panel/lib/graphql/generated/index.ts
- apps/admin-panel/lib/graphql/generated/mocks.ts
- core/accounting/src/balance_sheet/ledger/mod.rs
- core/accounting/src/ledger_account/value.rs
- core/accounting/src/primitives.rs
- core/accounting/src/profit_and_loss/ledger/mod.rs
- core/accounting/src/trial_balance/ledger/mod.rs
- core/accounting/tests/ledger_transaction.rs
- lana/admin-server/src/graphql/accounting/ledger_account.rs
- lana/admin-server/src/graphql/schema.graphql
On frontend part, only modifies usage of GraphQL. Names in the application itself are not changed.
> refactor: Rename balance range fields to align with Cala

- lana/app/src/authorization/seed.rs
- lib/authz/src/lib.rs
In casbin model's group definitions, the first subject is the one that is also a member of the second one. For example 'g, admin, user' means that role admin also has role user and thus admin is the more powerful role. In parent/child naming scheme, it is more natural to call the more powerful role (admin) 'parent' and the less powerful (user) 'child'.
This change brings alignment with this idea. Consequently, the order of roles in `add_role_hierarchy` method conforms to the order in casbin model.
> chore: In RBAC hierarchy call 'parent' the more powerful role

- apps/admin-panel/app/credit-facilities/[credit-facility-id]/repayment-plan/list.tsx
- apps/admin-panel/i18n.lock
- apps/admin-panel/messages/en.json
- apps/admin-panel/messages/es.json
- apps/customer-portal/app/credit-facilities/[credit-facility-id]/repayment-plan.tsx
- core/credit/src/credit_facility/entity.rs
- core/credit/src/disbursal/entity.rs
- core/credit/src/lib.rs
- core/credit/src/processes/activate_credit_facility/mod.rs
- core/credit/src/repayment_plan/entry.rs
The current state of facility disbursals is:
- disbursals are created as `DUE`
- are marked as `OVERDUE` at maturity
This PR is to adjust disbursal due dates on credit facility to reflect that disbursals are:
- `NOT_YET_DUE` until maturity
(we may also attach early repayment incentives/penalities on this state later on)
- `DUE` at maturity
- never become `OVERDUE` or `DEFAULTED` as of current implementation (se below)
In future we will likely
- introduce `OVERDUE` and use to control liquidation
- introduce `DEFAULTED` as a state that happens after liquidation date and likely never gets called since we should always be able to liquidate
> chore: adjust facility due date

- lana/customer-server/src/config.rs
- update customer server config so `aud()` returns `"https://customer-api/graphql"`
- `make check-code` *(fails: could not download Rust stable toolchain)*
> fix: customer server audience default

- bats/helpers.bash
We have a conditional server kill where it is only killed if the server was started inside the test suite. If there was already a running server instance then we'd like to leave it running after the test for local workflow purposes.
The change that prompted this is that we're not starting test in suite anymore because we're now using the `--setup-suite-file` flag with a global server start in there. Needs to be investigated whether this can be removed
> chore: remove stop_server force kill

- core/money/src/lib.rs
- lana/admin-server/src/graphql/accounting/ledger_account.rs
- lana/admin-server/src/graphql/schema.graphql
- lana/admin-server/src/primitives.rs
This is an artefact of ranged balances where we can correctly have negative net balance amounts depending on the date range selected.
> chore: make net balances signed

- core/credit/src/lib.rs
- core/credit/src/obligation/mod.rs
- lana/sim-bootstrap/src/scenarios/timely_payments.rs
This fixes the first bootstrap scenario where:
- we get an `OutstandingAmount` panic
- we generate all expected interest obligations
> fix: incomplete bootstrapped facility

- flake.nix
- lana/entity-rollups/src/lib.rs
we already have a lot of env variable we need to dig with. it had a mental overhead to have more (when working on flake.nix or .envrc) so we should remove this, unless there is a specific for why this could be dynamic
> chore: removing env var that don't need to change

- core/accounting/tests/helpers.rs
- core/credit/tests/helpers.rs
- core/deposit/tests/helpers.rs
- core/governance/src/policy/repo.rs
- lana/app/tests/helpers.rs
- lib/job/src/repo.rs
We use the name `PGHOST`:
https://github.com/GaloyMoney/lana-bank/blob/e6a3c16a837c5ae5e48eb719c381636442148ff2/flake.nix#L327
> chore: In tests, read 'PGHOST' env var instead of 'PG_HOST'

- core/credit/src/ledger/constants.rs
- core/credit/src/ledger/credit_facility_accounts.rs
- core/credit/src/ledger/mod.rs
- core/credit/src/ledger/templates/mod.rs
- core/credit/src/ledger/templates/reserve_for_liquidation.rs
- lana/entity-rollups/schemas/credit_facility_event_schema.json
- lana/entity-rollups/schemas/disbursal_event_schema.json
This PR adds a new ledger template for recording when we put an obligation into liquidation.
No existing outstanding amount accounts are touched in the template. This template simply records a new transaction in new memo accounts (memo because of where they'll be attached to the chart) to keep track of amounts reserved to be repaid via liquidation for obligations.
In future, this reserved balance will be:
- reduced, when repayments from liquidated capital are made
- reverted, when the obligation moves out of liquidation
> feat: add 'reserve for liquidation' ledger template

- Cargo.lock
- core/credit/src/jobs/wallet_collateral_sync.rs
- core/custody/src/custodian/client/mod.rs
- core/custody/src/custodian/notification.rs
- core/custody/src/event.rs
- core/custody/src/lib.rs
- core/custody/src/publisher.rs
- core/custody/src/wallet/entity.rs
- lib/bitgo/Cargo.toml
- lib/bitgo/src/wire.rs
When updating collateral via synchronization with custodians, we provided effective date as the current date (now).
This change replaces this current date with a suitable date provided by custodian, e. g. confirmation time on blockchain or similar.
> chore: Use balance update time provided by custodian

- apps/admin-panel/app/custodians/create.tsx
- core/custody/src/custodian/entity.rs
- lib/komainu/src/error.rs
- lib/komainu/src/lib.rs
Secret key for Komainu comes in standard DEM format, which contains multiple lines. An input form field joins all lines into one.
This change subsitutes input field with a textarea that preserves lines. Additionally, parsing secret keys fails with more graceful errors.
> chore: Allow to pass multiline secret key for Komainu

- bats/credit-facility-custody.bats
- lana/admin-server/src/custodian_webhooks.rs
We previously used webhook URL in form /PROVIDER/webhook but decided to swap the two parts into /webhook/PROVIDER.
> chore: Swap parts in webhook URL

- lib/job/src/poller.rs
The `poll_and_dispatch` method gets called hundreds of times per second, flooding tracing. This change demotes trace level of this method to TRACE. Overriding manually via env_logger may be possible.
> chore: Reduce tracing level of job.poll_and_dispatch

- core/credit/src/obligation/entity.rs
- core/credit/src/primitives/mod.rs
This is in prep for saving the due dates as `NaiveDate` type. This PR converts the current timestamps to `NaiveDate`s and then applies `start_of_day` to get the appropriate timestamp for things like comparisons and job scheduling
> chore: use start_of_day for obligation dates and expected status

- apps/admin-panel/app/withdrawals/[withdrawal-id]/details.tsx
- apps/admin-panel/app/withdrawals/list.tsx
https://github.com/GaloyMoney/volcano-wip/issues/451
Note: The ID is still present on the list page, but it does not have a link attached to it.
> chore: remove sumsub link from list page

- core/accounting/src/chart_of_accounts/entity.rs
- core/accounting/src/ledger_account/mod.rs
Children of ledger accounts were listed in no particular order (as returned by hash map), which made orientation in larger lists uneasy. This change returns them ordered by their account code.
> chore: Order children of a ledger account by account code

- Cargo.lock
- lana/sim-bootstrap/Cargo.toml
- lana/sim-bootstrap/src/scenarios/disbursal_different_months.rs
- lana/sim-bootstrap/src/scenarios/interest_late.rs
- lana/sim-bootstrap/src/scenarios/interest_under_payment.rs
- lana/sim-bootstrap/src/scenarios/principal_late.rs
- lana/sim-bootstrap/src/scenarios/principal_under_payment.rs
- lana/sim-bootstrap/src/scenarios/timely_payments.rs
This PR adds tracing to simulation scenarios. Additionally in `principal_under_payment_scenario`, eliminates raising error in a specific case.
> chore: Add tracing to simulation scenarios

- meltano/transform/dbt_project.yml
Drops the dbt posthook since we're not really using the output it generates anymore.
> chore: remove dbt posthook
