definitions/intermediate/int_accounts.sqlx
definitions/intermediate/int_approved_credit_facilities.sqlx
definitions/intermediate/int_customers.sqlx
definitions/outputs/dim_accounts.sqlx
definitions/outputs/dim_credit_facilities.sqlx
definitions/outputs/dim_customers.sqlx

This will make it easy to write queries about things like payments and interest accruals related to specific customers or credit facilities.

feat(reporting): link ledger accounts to customers and credit facilities

---

meltano/.gitignore
meltano/meltano.yml
meltano/orchestrate/airflow/airflow.cfg
meltano/orchestrate/airflow/dags/README.md
meltano/orchestrate/airflow/dags/meltano_dag_generator.py
meltano/orchestrate/airflow/webserver_config.py
meltano/plugins/utilities/airflow--apache.lock

- **fix: meltano alias in flake**
- **feat: add airflow orchestrator**

feat(reporting): add airflow orchestrator to meltano

---

meltano/transform/models/outputs/el-salvador-ssf/report_npb4_16_01_saldo_cuenta_xml.sql

In case we run into the permission errors solved by: https://github.com/GaloyMoney/lana-bank/pull/1303

chore(reporting): materialize regulatory reports

---

meltano/transform/dbt_project.yml
meltano/transform/macros/time-value-money/create_udfs.sql
meltano/transform/macros/time-value-money/udf_loan_convexity.sql
meltano/transform/macros/time-value-money/udf_loan_duration.sql
meltano/transform/macros/time-value-money/udf_loan_mac_duration.sql
meltano/transform/macros/time-value-money/udf_loan_mod_duration.sql
meltano/transform/macros/time-value-money/udf_loan_pv.sql
meltano/transform/macros/time-value-money/udf_loan_pv_delta_on_interest_rate_delta_with_convex.sql
meltano/transform/macros/time-value-money/udf_loan_ytm.sql
meltano/transform/macros/time-value-money/udf_loan_ytm_from_price.sql

recreating time value of money udfs in bq so they can be used in holistics
(had to expand the javascript inline as I couldn't quickly port the shorter dataform version with single js file reference, TODO later)

feat: dbt tvm udfs

---

Cargo.lock
core/chart-of-accounts/src/chart_of_accounts/entity.rs
core/chart-of-accounts/src/lib.rs
lana/admin-server/src/graphql/account.rs
lana/admin-server/src/graphql/financials/category.rs
lana/admin-server/src/graphql/financials/profit_and_loss.rs
lana/admin-server/src/graphql/schema.rs
lana/app/src/accounting_init/constants/mod.rs
lana/app/src/accounting_init/error.rs
lana/app/src/accounting_init/mod.rs
lana/app/src/accounting_init/primitives.rs
lana/app/src/accounting_init/seed/charts_of_accounts.rs
lana/app/src/accounting_init/seed/statements.rs
lana/app/src/app/error.rs
lana/app/src/app/mod.rs
lana/app/src/authorization/seed.rs
lana/app/src/lib.rs
lana/app/src/profit_and_loss/error.rs
lana/app/src/profit_and_loss/ledger/error.rs
lana/app/src/profit_and_loss/ledger/mod.rs
lana/app/src/profit_and_loss/mod.rs
lana/app/src/statement/mod.rs
lana/app/src/trial_balance/ledger/mod.rs
lana/ids/src/lib.rs
lana/rbac-types/src/action.rs
lana/rbac-types/src/object.rs

feat: add profit loss

---

meltano/transform/macros/time-value-money/udf_loan_ytm_from_price.sql

quick fix on a missing javascript function called within the udf

fix: dbt tvm udfs

---

meltano/transform/models/intermediate/el-salvador-ssf/int_npb4_16_01_saldo_cuenta_xml_raw.sql

The tables generating this report can be simplified in a future PR.

fix(reporting): remove balance sheet account set refernece in saldo_cuenta.xml

---

Makefile
flake.nix
meltano/.sqlfluff
meltano/transform/models/intermediate/credit_facilities/int_cf_agg_projected_cash_flows_timeseries.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_agg_projected_cash_flows_tvm_risk.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_collaterals.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_denormalized.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_disbursals.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_flatten.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_payments.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_projected_cash_flows_common.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_projected_cash_flows_timeseries.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_projected_cash_flows_tvm_risk.sql
meltano/transform/models/intermediate/credit_facilities/int_credit_facilities.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_numbers.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_time_value_of_money.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_values.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_customers_in_numbers.sql
meltano/transform/models/outputs/risk_management/kpi_credit_facilities.sql

- int_credit_facilities                         => initial terms, dates, flags and facility amount fact
- int_cf_disbursals                             => disbursals dates, flags and amount fact
- int_cf_collaterals                            => collaterals dates, flags and [abs_diff, total_collateral, collateral] facts
- int_cf_payments                               => payments dates, flags and [disbursement_amount, interest_amount] facts
- int_cf_denormalized                           => join of (int_credit_facilities, int_cf_disbursals, int_cf_collaterals, int_cf_payments)
- int_cf_flatten                                => one entry per c.f., latest of terms, total disbursed, total collateral, interest accrued, interest paid, principal paid
- int_cf_projected_cash_flows_common …

feat(reporting): dbt credit facility models

---

apps/admin-panel/app/credit-facilities/list.tsx
apps/admin-panel/app/loans/status-badge.tsx
apps/admin-panel/components/data-table/index.tsx
apps/admin-panel/components/paginated-table/index.tsx
lib/js/shared-web/global.css
lib/js/shared-web/src/ui/badge.tsx
lib/js/shared-web/tailwind.config.ts

+ also added different color for Pending Collateralization state

chore: padding in table rows

---

Makefile
meltano/.sqlfluffignore
meltano/transform/models/intermediate/credit_facilities/int_btc_price_simulation.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_agg_liquidation_cash_flows_tvm_risk.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_agg_projected_cash_flows_timeseries.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_agg_projected_cash_flows_tvm_risk.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_collaterals.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_denormalized.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_disbursals.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_flatten.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_payments.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_projected_cash_flows_common.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_projected_cash_flows_timeseries.sql
meltano/transform/models/intermediate/credit_facilities/int_cf_projected_cash_flows_tvm_risk.sql
meltano/transform/models/intermediate/credit_facilities/int_credit_facilities.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_collateral_in_values.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_numbers.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_time_value_of_money.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_values.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_customers_in_numbers.sql
meltano/transform/models/intermediate/int_approved_credit_facilities.sql
meltano/transform/models/intermediate/int_sumsub_applicants.sql
meltano/transform/models/outputs/risk_management/kpi_credit_facilities.sql
meltano/transform/models/staging/stg_sumsub_applicants.sql

collateral models for holistics kpi

feat: dbt collateral models

---

meltano/extract/tap-bitfinexapi/tap_bitfinexapi/client.py
meltano/extract/tap-bitfinexapi/tap_bitfinexapi/streams.py
meltano/extract/tap-bitfinexapi/tap_bitfinexapi/tap.py
meltano/extract/tap-sumsubapi/tap_sumsubapi/streams.py
meltano/transform/models/sources.yml
meltano/transform/models/staging/stg_bitfinex_ticker_price.sql
meltano/transform/models/staging/stg_sumsub_applicants.sql

Also improves names for the streams to avoid potential future conflicts with other exchanges or kyc providers.

feat(reporting): trades and order book streams for bitfinex api extractor

---

apps/admin-panel/lib/utils.ts
apps/customer-portal/lib/utils.ts

fix: https://github.com/GaloyMoney/lana-bank/issues/1424

fix: handel null date in credit facility

---

meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_collateral_in_values.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_numbers.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_time_value_of_money.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_credit_facilities_in_values.sql
meltano/transform/models/intermediate/credit_facilities/risk_management/int_customers_in_numbers.sql
meltano/transform/models/outputs/risk_management/kpi_credit_facilities.sql

- iteration over names vs title/labels for holistic, mostly esthetics 
- name convention for percent (100 [%]) versus ratio (1 [*100%])

feat: kpi short name clarification

---

apps/admin-panel/app/modules/balance-sheet-config-update.tsx
apps/admin-panel/app/modules/page.tsx
apps/admin-panel/i18n.lock
apps/admin-panel/lib/graphql/generated/index.ts
apps/admin-panel/messages/en.json
apps/admin-panel/messages/es.json
lana/app/src/authorization/seed.rs

built on top of: https://github.com/GaloyMoney/lana-bank/pull/1661

chore: balance sheet config ui

---

apps/admin-panel/app/ledger-account/[ledger-account-code]/page.tsx

fix: https://github.com/GaloyMoney/lana-bank/issues/1679

fix: ledger history amount should be in dollars

---

apps/admin-panel/app/trial-balance/page.tsx
apps/admin-panel/cypress/e2e/trial-balance.cy.ts
apps/admin-panel/i18n.lock
apps/admin-panel/messages/en.json
apps/admin-panel/messages/es.json

feat: add opening and closing balance ui

---

lana/app/src/app/mod.rs
lana/app/src/storage/mod.rs
lana/app/tests/gcs.rs

This PR makes the server startup without valid gcp credentials.

chore: startup without gcp creds

---

apps/admin-panel/cypress/e2e/credit-facilities.cy.ts
apps/admin-panel/cypress/support/commands.ts
apps/admin-panel/lib/utils.ts

The tests are passing now. However, there seems to be an issue with Netlify in the manuals and Storybook deployment.

fix: credit facility test

---

.github/workflows/check-code.yml

related to : https://github.com/GaloyMoney/lana-bank/pull/1235#discussion_r2021301754

chore: restore frontend check-code in acitons

---

Cargo.lock
Cargo.toml
core/accounting/src/journal/entry.rs
core/accounting/src/ledger_account/ledger/mod.rs
core/accounting/src/ledger_account/primitives.rs
core/credit/src/ledger/mod.rs
core/credit/tests/chart_of_accounts_integration.rs
core/deposit/src/ledger/mod.rs
core/deposit/tests/chart_of_accounts_integration.rs
lana/admin-server/src/graphql/accounting/ledger_account.rs
lana/app/src/balance_sheet/ledger/mod.rs
lana/app/src/cash_flow/ledger/mod.rs
lana/app/src/general_ledger/entry.rs
lana/app/src/profit_and_loss/ledger/mod.rs
lana/app/src/statement/mod.rs
lana/app/src/trial_balance/ledger/mod.rs

Demo of using new currency constants from https://github.com/GaloyMoney/cala/pull/376.
Draft until new Cala version released.

chore: Bump Cala version

---

apps/admin-panel/app/ledger-account/[ledger-account-ref]/page.tsx
apps/admin-panel/lib/graphql/generated/index.ts
apps/admin-panel/lib/graphql/generated/mocks.ts
core/accounting/src/journal/entry.rs
core/accounting/src/ledger_account/ledger/error.rs
core/accounting/src/ledger_account/ledger/mod.rs
core/accounting/src/ledger_account/mod.rs
lana/admin-server/src/graphql/accounting/journal_entry.rs
lana/admin-server/src/graphql/accounting/ledger_account.rs
lana/admin-server/src/graphql/schema.graphql

Backend part done, frontend not yet.

refactor: Use Journal Entry in Account History result

---

apps/admin-panel/app/globals.css
apps/admin-panel/next.config.mjs
apps/admin-panel/package.json
apps/customer-portal/app/globals.css
apps/customer-portal/next.config.mjs
apps/customer-portal/package.json

chore: use --turbo for nextjs to lunch faster

---

apps/admin-panel/app/journal/page.tsx
apps/admin-panel/i18n.lock
apps/admin-panel/lib/graphql/generated/index.ts
apps/admin-panel/messages/en.json
apps/admin-panel/messages/es.json

chore: add account name in journal

---

meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_03_documentos_clientes.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_04_titulares.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_05_agencias.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_06_productos.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_07_funcionarios_y_empleados.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_08_resumen_de_depósitos_garantizados.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_09_ajustes.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_01_cliente.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_02_depósitos.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_03_documentos_clientes.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_04_titulares.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_05_agencias.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_06_productos.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_07_funcionarios_y_empleados.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_08_resumen_de_depósitos_garantizados.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_09_ajustes.sql

feat: reg report nrsf 03 07 bank employees

---

meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_03_documentos_clientes.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_04_titulares.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_05_agencias.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_06_productos.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_01_cliente.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_02_depósitos.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_03_documentos_clientes.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_04_titulares.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_05_agencias.sql
meltano/transform/models/outputs/el-salvador-ssf/report_nrsf_03_06_productos.sql

feat: reg report nrsf 03 05 agencies

---

core/credit/src/credit_facility/entity.rs

These were added while exploring the fix for #1816

test: add more collateralization_ratio coverage

---

lib/cloud-storage/tests/gcs.rs

Asserting that `generate_download_link` works is plenty for this feature.

test: remove flaky assert in gcs.rs

---

.github/workflows/test-integration.yml

https://carlosbecker.com/posts/github-actions-disk-space/
explains how ubuntu-latest worker comes with a bunch of stuff that we might not use like 
Android SDK, Dotnet SDK, CodeQL Cache etc

perf: clean up space of integration test

---

.github/actions/setup-nix/action.yml

This reverts commit 09c519bbd0aeca07941974d4497421d24650d962.

revert: is it still necessary to rm stuff (#1853)

---

core/credit/src/credit_facility/balance.rs
core/credit/src/jobs/interest_accruals.rs

Interest should only be calculated on all disbursed outstanding amounts

fix: remove calculating interest on interest 

---

core/credit/src/obligation/entity.rs

fix: ignore due/overdue record if paid

---

scripts/reg-report-xml-validation/Makefile
scripts/reg-report-xml-validation/main.py
scripts/reg-report-xml-validation/requirements.txt
scripts/reg-report-xml-validation/samples/persona-bad.xml
scripts/reg-report-xml-validation/samples/persona.xml
scripts/reg-report-xml-validation/samples/persona.xsd
typos.toml

simple validation, failing if not conform & reporting errors
samples of good and bad cases

feat: reg report xml validation script

---

apps/admin-panel/app/credit-facilities/[credit-facility-id]/history.tsx
apps/admin-panel/app/credit-facilities/[credit-facility-id]/layout.tsx
apps/admin-panel/app/credit-facilities/[credit-facility-id]/page.tsx
apps/admin-panel/i18n.lock
apps/admin-panel/lib/graphql/generated/index.ts
apps/admin-panel/messages/en.json
apps/admin-panel/messages/es.json
apps/customer-portal/app/credit-facilities/[credit-facility-id]/history.tsx
apps/customer-portal/app/credit-facilities/[credit-facility-id]/page.tsx

chore: rename credit facility transaction to history

---

core/credit/src/obligation/entity.rs
core/credit/src/payment_allocation/entity.rs
core/credit/src/publisher.rs
core/credit/src/repayment_plan/mod.rs

This is to also produce a repayment plan before activation using the full facility amount as a hypothetical disbursal and calculating interest accruals based on this

chore: populate repayment plan pre-activation

---

bats/accounting.bats
core/accounting/src/chart_of_accounts/entity.rs

test: charts add trial balance accounts

---

meltano/transform/macros/util/drop_old_relations.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrp_41_02_referencia.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrp_41_03_referencia_garantia.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrp_41_07_garantia_pignorada.sql
meltano/transform/models/intermediate/int_accounts.sql
meltano/transform/models/intermediate/int_approved_credit_facilities.sql
meltano/transform/models/intermediate/int_approved_credit_facility_loan_cash_flows.sql
meltano/transform/models/intermediate/int_approved_credit_facility_loans.sql
meltano/transform/models/intermediate/int_collateral_events.sql
meltano/transform/models/intermediate/int_credit_facility_accrual_cycle_events.sql
meltano/transform/models/intermediate/int_credit_facility_collateral_events.sql
meltano/transform/models/intermediate/int_credit_facility_events.sql
meltano/transform/models/intermediate/int_credit_facility_events_combo.sql
meltano/transform/models/intermediate/int_disbursal_events.sql
meltano/transform/models/intermediate/int_interest_accrual_cycle_events.sql
meltano/transform/models/intermediate/int_obligation_events.sql
meltano/transform/models/intermediate/int_payment_events.sql
meltano/transform/models/sources.yml
meltano/transform/models/staging/stg_collateral_events.sql
meltano/transform/models/staging/stg_disbursal_events.sql
meltano/transform/models/staging/stg_interest_accrual_cycle_events.sql
meltano/transform/models/staging/stg_obligation_events.sql
meltano/transform/models/staging/stg_payment_events.sql

- accounting for changes in credit facility events changes
- accounting for credit facility disbursal, collateral, interest and payment events spin off into a different tables
- adding an intermediate step for events json decoding & "aggregating"/"serializing"
- update credit facility dependent transforms to use the above mentioned  intermediate transforms

fix: data pipeline events

---

core/accounting/src/chart_of_accounts/csv.rs

_Re-implements PR #1624 & builds on #1623_
Allows parsing the balance-type from any last position column in csv, instead of locking it to the 5th column.
Setting the balance type in the right column was not intuitive when configuring the chart import in #2029

refactor: make balance_type parsing more flexible

---

apps/admin-panel/app/actions/list.tsx
apps/admin-panel/app/audit/list.tsx
apps/admin-panel/app/committees/list.tsx
apps/admin-panel/app/credit-facilities/[credit-facility-id]/disbursals/list.tsx
apps/admin-panel/app/credit-facilities/[credit-facility-id]/history.tsx
apps/admin-panel/app/credit-facilities/[credit-facility-id]/repayment-plan/list.tsx
apps/admin-panel/app/credit-facilities/list.tsx
apps/admin-panel/app/customers/[customer-id]/credit-facilities/list.tsx
apps/admin-panel/app/customers/[customer-id]/transactions.tsx
apps/admin-panel/app/disbursals/list.tsx
apps/admin-panel/app/journal/page.tsx
apps/admin-panel/app/ledger-account/[ledger-account-ref]/page.tsx
apps/admin-panel/app/transaction-templates/[transaction-template-code]/page.tsx
apps/admin-panel/components/date-with-tooltip/index.tsx
apps/admin-panel/cypress/e2e/balance-sheet.cy.ts
apps/admin-panel/cypress/e2e/profit-and-loss.cy.ts
apps/admin-panel/lib/utils.ts

+ Introduces locale-aware date formatting.
+ Adds DateWithTooltip: shows a short, browser-locale date in tables/lists and reveals the full date + time on hover.

chore: standardize date formats and add tooltip timestamps

---

Makefile
bats/y-pipeline_events.bats
meltano/meltano.yml
meltano/transform/dbt_project.yml
meltano/transform/macros/util/drop_all_relations.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrp_41_02_referencia.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrp_41_03_referencia_garantia.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrp_41_07_garantia_pignorada.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_01_cliente.sql
meltano/transform/models/intermediate/el-salvador-ssf/int_nrsf_03_02_depósitos.sql
meltano/transform/models/intermediate/int_approved_credit_facilities.sql
meltano/transform/models/intermediate/int_approved_credit_facility_loan_cash_flows.sql
meltano/transform/models/intermediate/int_approved_credit_facility_loans.sql
meltano/transform/models/intermediate/int_collateral_events.sql
meltano/transform/models/intermediate/int_credit_facility_accrual_cycle_events.sql
meltano/transform/models/intermediate/int_credit_facility_collateral_events.sql
meltano/transform/models/intermediate/int_credit_facility_events.sql
meltano/transform/models/intermediate/int_credit_facility_events_combo.sql
meltano/transform/models/intermediate/int_disbursal_events.sql
meltano/transform/models/intermediate/int_interest_accrual_cycle_events.sql
meltano/transform/models/intermediate/int_obligation_events.sql
meltano/transform/models/intermediate/int_payment_events.sql
meltano/transform/models/static/el-salvador-ssf/static_ncb_022_porcentaje_reservas_saneamiento.md
meltano/transform/models/static/el-salvador-ssf/static_ncb_022_porcentaje_reservas_saneamiento.sql
meltano/transform/models/static/el-salvador-ssf/static_ncb_022_porcentaje_reservas_saneamiento.yml

- add bats test to validate pipeline events assumptions
- fix some transforms
- add makefile tasks to clean up bq

chore: pipeline chores

---

flake.lock
meltano.nix

Reverts GaloyMoney/lana-bank#2155

revert: "chore: bump python to 3.12 for faster build"

---

lana/app/src/report/entity.rs

working on bring back some symmetry with file related events

chore: unused event

---

core/credit/src/disbursal/entity.rs
core/credit/src/lib.rs
core/credit/src/processes/activate_credit_facility/mod.rs
lana/entity-rollups/schemas/disbursal_event_schema.json

The liquidation date from Disbursal will eventually be forwarded to new obligations

chore: add liquidation date to disbursal entity

---

meltano/transform/models/staging/stg_account_balances.sql
meltano/transform/models/staging/stg_account_set_member_account_sets.sql
meltano/transform/models/staging/stg_account_set_member_accounts.sql
meltano/transform/models/staging/stg_account_sets.sql
meltano/transform/models/staging/stg_accounts.sql
meltano/transform/models/staging/stg_credit_facility_events.sql
meltano/transform/models/staging/stg_customer_events.sql
meltano/transform/models/staging/stg_deposit_accounts.sql
meltano/transform/models/staging/stg_deposit_events.sql
meltano/transform/models/staging/stg_withdrawal_events.sql
meltano/transform/models/staging/stg_withdrawals.sql

Reverts GaloyMoney/lana-bank#2218
now that tables updated,
to avoid refreshing all the time

revert: fix full refresh incremental tables

---

core/credit/src/disbursal/entity.rs
core/credit/src/interest_accrual_cycle/entity.rs
core/credit/src/jobs/obligation_liquidation.rs
core/credit/src/ledger/credit_facility_accounts.rs
core/credit/src/ledger/mod.rs
core/credit/src/lib.rs
core/credit/src/liquidation_process/entity.rs
core/credit/src/obligation/entity.rs
core/credit/src/obligation/mod.rs
lana/entity-rollups/schemas/interest_accrual_cycle_event_schema.json
lana/entity-rollups/schemas/liquidation_process_event_schema.json
lana/entity-rollups/schemas/obligation_event_schema.json

~**_DO NOT MERGE_ before #2223**~
Call ledger template from liquidation job

chore: integrate liquidation ledger template in use-cases

---

meltano/transform/models/sources.yml
meltano/transform/models/staging/rollups/stg_core_approval_process_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_chart_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_collateral_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_committee_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_credit_facility_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_custodian_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_customer_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_deposit_account_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_deposit_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_disbursal_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_document_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_interest_accrual_cycle_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_liquidation_process_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_manual_transaction_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_obligation_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_payment_allocation_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_payment_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_permission_set_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_policy_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_role_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_terms_template_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_user_events_rollup.sql
meltano/transform/models/staging/rollups/stg_core_withdrawal_events_rollup.sql

- add new sources for the roll ups
- correct customer source
- add incremental tables for roll ups

feat: intermediate rollups

---

meltano/utilities/generate-es-reports/generate_es_reports/__init__.py

Some norms require xml, some require pipe delimited text files.  This PR implements these requirements for the norms we're generating.
Also groups reports into sub directories to add a layer of structure to the list of reports.

feat(reporting): serialize reports differently depending on norm requirements

---

apps/admin-panel/app/app-layout.tsx
apps/admin-panel/app/command-menu.tsx
apps/admin-panel/app/create.tsx
apps/admin-panel/app/customers/[customer-id]/balances.tsx
apps/admin-panel/app/customers/[customer-id]/details.tsx
apps/admin-panel/app/customers/[customer-id]/layout.tsx
apps/admin-panel/components/command-menu/menu-sections.tsx
apps/admin-panel/components/command-menu/search-results.tsx
apps/admin-panel/components/details/card/index.tsx
apps/admin-panel/components/public-id-badge.tsx
apps/admin-panel/components/search-and-command.tsx
apps/admin-panel/hooks/use-command-menu.ts
apps/admin-panel/hooks/use-public-id-search.ts
apps/admin-panel/i18n.lock
apps/admin-panel/lib/graphql/generated/index.ts
apps/admin-panel/messages/en.json
apps/admin-panel/messages/es.json

feat: public id UI

---

flake.nix
meltano.nix

This PR is to fix the issue where the tests weren't actually affecting the final derivation and disabling the tests. It also adds more packages with testing issues to skip.
- Related issue with getting these to be applied properly: https://discourse.nixos.org/t/disable-python-testing-in-flake/46381/2

fix: meltano nix build

---

core/money/Cargo.toml
core/money/src/lib.rs
lana/app/Cargo.toml

separate the "feature enablement" from the testing part

refactor: add graphql feature to core/money

---

core/credit/Cargo.toml
core/deposit/Cargo.toml
lana/app/migrations/20250729184207_create_core_user_events_rollup.sql
lana/app/migrations/20250729184208_create_core_role_events_rollup.sql
lana/app/migrations/20250729184209_create_core_permission_set_events_rollup.sql
lana/app/migrations/20250729184210_create_core_approval_process_events_rollup.sql
lana/app/migrations/20250729184211_create_core_committee_events_rollup.sql
lana/app/migrations/20250729184212_create_core_policy_events_rollup.sql
lana/app/migrations/20250729184213_create_core_customer_events_rollup.sql
lana/app/migrations/20250729184214_create_core_deposit_account_events_rollup.sql
lana/app/migrations/20250729184215_create_core_deposit_events_rollup.sql
lana/app/migrations/20250729184216_create_core_withdrawal_events_rollup.sql
lana/app/migrations/20250729184217_create_core_custodian_events_rollup.sql
lana/app/migrations/20250729184218_create_core_collateral_events_rollup.sql
lana/app/migrations/20250729184219_create_core_credit_facility_events_rollup.sql
lana/app/migrations/20250729184220_create_core_disbursal_events_rollup.sql
lana/app/migrations/20250729184221_create_core_interest_accrual_cycle_events_rollup.sql
lana/app/migrations/20250729184222_create_core_obligation_events_rollup.sql
lana/app/migrations/20250729184223_create_core_payment_events_rollup.sql
lana/app/migrations/20250729184224_create_core_payment_allocation_events_rollup.sql
lana/app/migrations/20250729184225_create_core_terms_template_events_rollup.sql
lana/app/migrations/20250729184226_create_core_chart_events_rollup.sql
lana/app/migrations/20250729184227_create_core_liquidation_process_events_rollup.sql
lana/app/migrations/20250729184228_create_core_document_events_rollup.sql
lana/app/migrations/20250729184229_create_core_manual_transaction_events_rollup.sql
lana/entity-rollups/src/templates/rollup_table_only.sql.hbs
lana/entity-rollups/src/templates/rollup_trigger_function.sql.hbs

The relevant changes are in the `*.hbs` template files - the rest of the diff is regenerating the migrations.

refactor: Insert in rollups

---

meltano/transform/models/intermediate/rollups/int_core_interest_accrual_cycle_events_rollup_sequence.sql
meltano/transform/models/staging/stg_bitfinex_trades.sql

fixes based on staging error logs
will review once staging runs 100% success

fix: pipeline 20250829

---

core/credit/src/processes/approve_credit_facility_proposal/job.rs

Fixes issue in sim-bootstrap where credit facilities never get approved/activated

fix: credit proposal approve job overriding correct credit approve job

---

apps/admin-panel/app/ledger-accounts/[ledger-account-ref]/page.tsx
apps/admin-panel/app/ledger-transaction/[ledger-transaction-id]/page.tsx
apps/admin-panel/i18n.lock
apps/admin-panel/lib/graphql/generated/index.ts
apps/admin-panel/messages/en.json
apps/admin-panel/messages/es.json

chore: link ledger view to entity

---

meltano/meltano.yml
meltano/transform/models/intermediate/rollups/int_core_credit_facility_events_rollup_sequence.sql
meltano/transform/models/intermediate/rollups/int_core_credit_facility_proposal_events_rollup.sql
meltano/transform/models/intermediate/rollups/int_core_credit_facility_proposal_events_rollup_sequence.sql
meltano/transform/models/sources.yml
meltano/transform/models/staging/rollups/stg_core_credit_facility_proposal_events_rollup.sql

- add new credit facility proposal relations
- reference new proposals relations in credit facility

feat: credit facility proposal integration
